version: "2"
services:
  my-wpdb:
    image: mariadb
    ports:
      - "8081:3306"
    volumes:
      - my-datavolume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ChangeMeIfYouWant
  my-wp:
    image: wordpress
    volumes:
      - ./:/var/www/html/web/wp/
    ports:
      - "8080:80"
    links:
      - my-wpdb:mysql
    environment:
      WORDPRESS_DB_PASSWORD: ChangeMeIfYouWant
volumes:
  my-datavolume:
